services:
  - type: web
    name: yandex-market-automation
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: D2D_API_KEY
        sync: false
      - key: HUMBLE_API_KEY
        sync: false
      - key: YANDEX_TOKEN
        sync: false
      - key: BITRIX_WEBHOOK_URL
        sync: false
